### ISSUE TITLE
PMX file support needed

### ISSUE THREAD

**Issue by bear0830** [takahirox/mmd-viewer-js#2]
mmd-viewer-js seems to support PMD files. How about PMX files?

**Comment by takahirox** [comment]
Please use `Three.js` `MMDLoader` I've been working on instead.

https://threejs.org/examples/#webgl_loader_mmd

Probably I won't update this `mmd-viewer-js` project anymore except for some minor optimization.

**Comment by Ry3yr** [comment]
This webgl_loader_mmd will throw a 
```
Uncaught (in promise) RuntimeError: abort(RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info.). Build with -s ASSERTIONS=1 for more info.
    at oa (ammo.wasm.js:18:190)
    at ammo.wasm.js:24:350
```

(I took the entire unzipped repo https://github.com/mrdoob/three.js/blob/master/examples/ )

I'm not sure why..
What could be different between this and the example on threejs.org ?

![Screenshot_2024-03-18-19-57-17](https://github.com/takahirox/mmd-viewer-js/assets/17431197/45b4f20b-0f97-454d-bf33-4696cfe63fbf)
